# Generated by Django 5.2.7 on 2025-10-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisAnggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jenis', models.CharField(max_length=20, unique=True)),
                ('nama_jenis', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('BELANJA_PEGAWAI', 'Belanja Pegawai'), ('BELANJA_BARANG_JASA', 'Belanja Barang dan Jasa'), ('BELANJA_MODAL', 'Belanja Modal'), ('BELANJA_HIBAH', 'Belanja Hibah'), ('BELANJA_BANTUAN_SOSIAL', 'Belanja Bantuan Sosial')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Jenis Anggaran',
                'db_table': 'jenis_anggaran',
            },
        ),
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kabkota', models.CharField(max_length=4, unique=True)),
                ('nama_kabkota', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('KABUPATEN', 'Kabupaten'), ('KOTA', 'Kota')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kabupaten/Kota',
                'db_table': 'kabupaten_kota',
            },
        ),
        migrations.CreateModel(
            name='ProgramKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_program', models.CharField(max_length=20, unique=True)),
                ('nama_program', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Program Kegiatan',
                'db_table': 'program_kegiatan',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.CharField(max_length=2, unique=True)),
                ('nama_provinsi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
                'db_table': 'provinsi',
            },
        ),
        migrations.CreateModel(
            name='AnggaranDaerah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_anggaran', models.IntegerField()),
                ('pagu_anggaran', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realisasi_anggaran', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sisa_anggaran', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('persentase_realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('RENCANA', 'Rencana'), ('DISETUJUI', 'Disetujui'), ('DIREALISASI', 'Direalisasi'), ('SELESAI', 'Selesai')], default='RENCANA', max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggaran', to='budget.jenisanggaran')),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggaran', to='budget.kabupatenkota')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggaran', to='budget.programkegiatan')),
            ],
            options={
                'verbose_name_plural': 'Anggaran Daerah',
                'db_table': 'anggaran_daerah',
                'ordering': ['-tahun_anggaran', '-pagu_anggaran'],
            },
        ),
        migrations.AddField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupaten_kota', to='budget.provinsi'),
        ),
        migrations.CreateModel(
            name='RealisasiBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('tahun', models.IntegerField()),
                ('jumlah_realisasi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisasi_bulanan', to='budget.anggarandaerah')),
            ],
            options={
                'verbose_name_plural': 'Realisasi Bulanan',
                'db_table': 'realisasi_bulanan',
                'ordering': ['tahun', 'bulan'],
                'unique_together': {('anggaran', 'bulan', 'tahun')},
            },
        ),
    ]
